### ISSUE TITLE
scans are much slower now

### ISSUE THREAD

**Issue by DanielRuf** [VirusTotal/yara-ci-issues#10]
current scan:

<img width="474" alt="Bildschirmfoto 2022-01-29 um 12 50 59" src="https://user-images.githubusercontent.com/827205/151659919-b64d6720-922c-4b0c-b816-e0a2c06f7620.png">

previous scans:

<img width="432" alt="Bildschirmfoto 2022-01-29 um 12 51 50" src="https://user-images.githubusercontent.com/827205/151659931-65cd19b1-3ced-4b6f-a943-4254c12c9dac.png">

**Comment by DanielRuf** [comment]
Interesting; I have run the old CI job again (from 20 days ago) and now it results in this:

<img width="474" alt="Bildschirmfoto 2022-01-29 um 12 54 53" src="https://user-images.githubusercontent.com/827205/151660032-dc96769e-15dd-45ef-b2fe-2eb8537b1561.png">

**Comment by Zohiartze** [comment]
Scan times can vary a lot from run to run as they can be affected by a number of factors, the primary one being temporary  high system loads due to many jobs running concurrently. 

Regarding the incongruence of the results you got in the check-run reports and after analyzing the logs, we have fixed a bug by which the system wasn't recovering properly to some kind of transient errors.

Could you please re-run the jobs and check that the results are ok now?

**Comment by DanielRuf** [comment]
> Could you please re-run the jobs and check that the results are ok now?

Thanks, I will check this week and let you know.

**Comment by DanielRuf** [comment]
Seems to be resolved now, thanks for letting me know that it was fixed.
